apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-recommend-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-recommend-service
  template:
    metadata:
      labels:
        app: go-recommend-service
      annotations:
        vault.security.banzaicloud.io/vault-addr: "http://vault.vault:8200"
        vault.security.banzaicloud.io/vault-role: "webapp"
        vault.security.banzaicloud.io/vault-skip-verify: "true"
        vault.security.banzaicloud.io/vault-path: "kubernetes"
    spec:
      serviceAccountName: default
      containers:
      - name: go-recommend-service
        image: go-recommend-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8082
        env:
        - name: SECRET_USERNAME
          value: vault:secret/data/webapp/config#username
        - name: SECRET_PASSWORD
          value: vault:secret/data/webapp/config#password
